-- BLStudio CRM — Seed de los 30 posts de julio 2026 (hilo narrativo)
-- Correr DESPUES de schema.sql. Idempotente por (date).

insert into posts (date, dia_narrativo, semana, arc, topic, format, pilar, hook, status) values
  ('2026-07-02', 1, 1, 'problema', 'Apertura de la serie', 'Historia', 1, 'Si alguien busca ''hamburguesas [ciudad]'' ahora mismo… ¿aparecés?', 'approved'),
  ('2026-07-03', 2, 1, 'problema', 'El costo invisible', 'Carrusel', 1, 'Cada día sin aparecer en Google son pedidos que se van a la competencia. Sin que te avisen.', 'approved'),
  ('2026-07-04', 3, 1, 'problema', 'La trampa de Instagram', 'Historia', 1, 'Construiste 5 años de negocio sobre una plataforma que no es tuya. Un día te cierran la cuenta y perdés todo.', 'scheduled'),
  ('2026-07-05', 4, 1, 'problema', 'El quilombo de los pedidos', 'Reel', 2, 'Un domingo a las 20hs: 40 DMs, 12 capturas, 3 pedidos que llegaron mal. Eso tiene solución.', 'copy_ready'),
  ('2026-07-06', 5, 1, 'problema', 'El cliente que no vuelve', 'Historia', 3, 'No es que no le gustó tu burger. Es que no tuvo forma de recordarte cuando volvió a tener hambre.', 'copy_ready'),
  ('2026-07-07', 6, 1, 'problema', 'La web vieja', 'Carrusel', 4, 'Una web sin actualizar desde 2020 no es presencia digital. Es evidencia de que no le das bola al negocio.', 'image_ready'),
  ('2026-07-08', 7, 1, 'problema', 'Resumen de la semana', 'Carrusel', 4, '7 formas en que tu negocio gastronómico pierde plata hoy, sin que lo notes.', 'copy_ready'),
  ('2026-07-09', 8, 2, 'realidad', 'El antes y el después', 'Carrusel', 2, 'Antes: WhatsApp, caos, errores. Después: el pedido llega a la cocina solo.', 'draft'),
  ('2026-07-10', 9, 2, 'realidad', 'Google Business', 'Historia', 1, 'El 80% de los gastronómicos en Argentina no verificó su local en Google. Están regalando clientes.', 'draft'),
  ('2026-07-11', 10, 2, 'realidad', 'El primer pedido online', 'Historia', 2, 'El primer pedido que entra solo, sin que atiendas un DM, se siente distinto. Como cobrar mientras dormís.', 'draft'),
  ('2026-07-12', 11, 2, 'realidad', 'La cocina en tiempo real', 'Reel', 2, 'Tu cocinero no debería enterarse del pedido cuando vos le gritás desde el mostrador.', 'draft'),
  ('2026-07-13', 12, 2, 'realidad', 'Fidelización real', 'Historia', 3, 'El cliente que vuelve cuesta 5 veces menos que conseguir uno nuevo. ¿Cuántos te vuelven?', 'draft'),
  ('2026-07-14', 13, 2, 'realidad', 'La pregunta incómoda', 'Historia', 4, '¿Cuánto estimás que perdiste este mes por no aparecer en Google? Calculalo en serio.', 'draft'),
  ('2026-07-15', 14, 2, 'realidad', 'El sistema vs el improviso', 'Carrusel', 2, 'Improviso: cansás, cometés errores, no escalás. Sistema: crecés sin depender de tu memoria.', 'draft'),
  ('2026-07-16', 15, 3, 'solucion', 'Presentación de BLStudio', 'Historia', 5, 'En BLStudio hacemos una sola cosa: digitalizar la operación de tu restaurante. Y lo hacemos bien.', 'draft'),
  ('2026-07-17', 16, 3, 'solucion', 'El SEO como diferencial', 'Carrusel', 1, 'Le hicimos SEO a un cliente. En 3 días apareció primero en Google. En un mes duplicó los pedidos de buscador.', 'draft'),
  ('2026-07-18', 17, 3, 'solucion', 'El catálogo digital', 'Historia', 2, 'Tu menú online con tu identidad, tus precios, tus reglas. Sin comisiones de terceros.', 'draft'),
  ('2026-07-19', 18, 3, 'solucion', 'La vista de cocina', 'Reel', 2, 'Una tablet en la cocina. El pedido llega solo, en tiempo real, sin gritos. Así trabajan nuestros clientes.', 'draft'),
  ('2026-07-20', 19, 3, 'solucion', 'La fidelización con sistema', 'Historia', 3, 'Soles, figuritas, puntos. El cliente acumula, canjea, vuelve. Automatizado. Sin que hagas nada extra.', 'draft'),
  ('2026-07-21', 20, 3, 'solucion', 'El precio', 'Historia', 5, 'USD 150 de setup. USD 35 por mes. Menos que 3 burgers de las que vendés en un domingo.', 'draft'),
  ('2026-07-22', 21, 3, 'solucion', 'La propuesta completa', 'Carrusel', 5, 'Landing + catálogo + gestión + fidelización + SEO. Todo integrado. Todo a medida. Todo tuyo.', 'draft'),
  ('2026-07-23', 22, 4, 'prueba', 'Caso Tcocina', 'Carrusel', 5, '150 burgers el domingo. Este es el sistema que tiene Tcocina en Olavarría. Funciona de verdad.', 'draft'),
  ('2026-07-24', 23, 4, 'prueba', 'Caso Doña Clara', 'Historia', 5, 'Una rosticería con 20 años y todo manual. En 2 semanas digitalizamos su operación completa.', 'draft'),
  ('2026-07-25', 24, 4, 'prueba', 'El SEO con captura', 'Historia', 1, 'aceitelaventera.com — primero en Google para su búsqueda. Captura real, no promesa.', 'draft'),
  ('2026-07-26', 25, 4, 'prueba', 'Objeción 1: el precio', 'Historia', 4, '¿Caro? Un error de pedido el domingo te cuesta más que todo un mes de mensualidad.', 'draft'),
  ('2026-07-27', 26, 4, 'prueba', 'Objeción 2: la tecnología', 'Reel', 4, 'No necesitás saber nada de tecnología. Vos cocinás. El sistema hace el resto.', 'draft'),
  ('2026-07-28', 27, 4, 'prueba', 'La urgencia real', 'Historia', 1, 'En tu ciudad, el primero que aparece en Google se queda con la búsqueda. El segundo queda invisible.', 'draft'),
  ('2026-07-29', 28, 4, 'prueba', 'Social proof', 'Carrusel', 5, 'Estos son los negocios que ya tienen el sistema. ¿El tuyo cuándo?', 'draft'),
  ('2026-07-30', 29, 4, 'prueba', 'La oferta', 'Historia', 5, 'Si querés que arranquemos: mandame un mensaje hoy. Te cuento qué incluye y cómo arranca.', 'draft'),
  ('2026-07-31', 30, 4, 'prueba', 'Cierre narrativo', 'Historia', 5, '30 días, una sola pregunta: ¿seguís esperando o empezamos?', 'draft');
